/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApplyRouteImport } from './routes/_app/apply'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppApplicationsAppIdRouteImport } from './routes/_app/applications.$appId'
import { Route as AppAdminApplicationsRouteImport } from './routes/_app/admin/applications'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyRoute = AppApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsAppIdRoute = AppApplicationsAppIdRouteImport.update({
  id: '/applications/$appId',
  path: '/applications/$appId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApplicationsRoute = AppAdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apply': typeof AppApplyRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/admin/applications': typeof AppAdminApplicationsRoute
  '/applications/$appId': typeof AppApplicationsAppIdRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apply': typeof AppApplyRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/admin/applications': typeof AppAdminApplicationsRoute
  '/applications/$appId': typeof AppApplicationsAppIdRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/apply': typeof AppApplyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/admin/applications': typeof AppAdminApplicationsRoute
  '/_app/applications/$appId': typeof AppApplicationsAppIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apply'
    | '/dashboard'
    | '/profile'
    | '/admin/applications'
    | '/applications/$appId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apply'
    | '/dashboard'
    | '/profile'
    | '/admin/applications'
    | '/applications/$appId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/apply'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/admin/applications'
    | '/_app/applications/$appId'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply': {
      id: '/_app/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AppApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/$appId': {
      id: '/_app/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/applications/$appId'
      preLoaderRoute: typeof AppApplicationsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/applications': {
      id: '/_app/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AppAdminApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplyRoute: typeof AppApplyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppAdminApplicationsRoute: typeof AppAdminApplicationsRoute
  AppApplicationsAppIdRoute: typeof AppApplicationsAppIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplyRoute: AppApplyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppAdminApplicationsRoute: AppAdminApplicationsRoute,
  AppApplicationsAppIdRoute: AppApplicationsAppIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
